# path for the YAPT executable
yapt_path: ~/git_prog/yapt/build

# path for the YAPT functions
function_path: ~/git_prog/yapt/functions

# path for storing the images
output_image_path: images

# params file
params_files: params.csv

